import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Footer from '@/components/ui/Footer'
import Navbar from '@/components/ui/Navbar'
import FooterLinkSection from '@/components/ui/FooterLinkSection'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Owlbs',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="pt-16">
          {children}
        </div>
        <FooterLinkSection />
        <Footer />
      </body>
    </html>
  );
}
